# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-22 02:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockvizrequest',
            name='path',
            field=models.TextField(null=True),
        ),
    ]
