# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-15 23:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0008_addressvizrequest_tx_offset'),
    ]

    operations = [
        migrations.AddField(
            model_name='addressvizrequest',
            name='comment',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='tracetxvizrequest',
            name='comment',
            field=models.TextField(null=True),
        ),
    ]
