# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-16 00:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0009_auto_20160615_2353'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockvizrequest',
            name='comment',
            field=models.TextField(null=True),
        ),
    ]
