# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-26 16:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_auto_20160422_0237'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blockvizrequest',
            old_name='rendered',
            new_name='completed',
        ),
    ]
