# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-10 23:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0006_auto_20160510_1718'),
    ]

    operations = [
        migrations.CreateModel(
            name='TraceTxVizRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('hash_index', models.TextField()),
                ('path', models.TextField(null=True)),
                ('completed', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
