# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-27 17:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_auto_20160426_1621'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcomponent',
            name='transactions',
        ),
        migrations.AddField(
            model_name='subcomponent',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 4, 27, 17, 31, 49, 580689, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subcomponent',
            name='path',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='subcomponent',
            name='txs',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='subcomponent',
            name='txs_length',
            field=models.IntegerField(null=True),
        ),
    ]
