# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-03 01:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0007_tracetxvizrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='addressvizrequest',
            name='tx_offset',
            field=models.IntegerField(default=0),
        ),
    ]
